"""Wire message for peer-to-peer activation push.

Miners push completed activations directly to a randomly selected peer in the
next (or previous, for backward) layer instead of routing through the
orchestrator's activation_state/activation_assignment tables.

The message is serialised via msgpack inside the P2PRouter routed envelope.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from common.iroh.p2p_protocol import P2PResponseStatus


class ActivationPushNackError(Exception):
    """Raised when receiver returns a non-SUCCESS ack for a push."""

    def __init__(self, status: P2PResponseStatus, message: str = ""):
        self.status = status
        super().__init__(message or f"Activation push NACK: {status.name}")


def encode_push_ack(status: P2PResponseStatus = P2PResponseStatus.SUCCESS) -> bytes:
    """Encode a single-byte ack for an activation push."""
    return bytes([status])


def decode_push_ack(data: bytes) -> P2PResponseStatus:
    """Decode a single-byte ack from an activation push response."""
    if not data:
        return P2PResponseStatus.ERROR
    try:
        return P2PResponseStatus(data[0])
    except ValueError:
        return P2PResponseStatus.ERROR


class ActivationPushMessage(BaseModel):
    """Payload pushed from one miner to a peer in the adjacent layer.

    Attributes:
        activation_id:    Stable ID for this activation (generated by the
                          layer-0 miner; preserved throughout the forward and
                          backward journey).
        direction:        ``"forward"`` or ``"backward"``.
        source_hotkey:    SS58 address of the sending miner.
        source_p2p_node_ids:  P2P node IDs of the sender so the
                          recipient can push the backward gradient back.
        tensor_bytes:     ``torch.save``-serialised tensor.
        source_layer:     Training layer index of the sending miner (optional
                          for legacy messages; recipients should validate when set).
        target_layer:     Training layer index of the intended recipient (optional
                          for legacy messages; recipients should validate when set).
    """

    activation_id: str
    direction: str
    source_hotkey: str
    source_p2p_node_ids: list[str] = Field(default_factory=list)
    tensor_bytes: bytes = b""
    # Presigned S3 URL for the original text sample — populated by layer-0 so
    # the last-layer miner can download target labels without querying the orchestrator.
    sample_path: str | None = None
    source_layer: int | None = None
    target_layer: int | None = None
