"""Pydantic message: activation push between adjacent-layer miners.

Moved here from `common.iroh.activation_push` as part of the iota-sdk
migration — the model is iota_mvp's domain (training-layer specifics)
and stays out of the SDK; only the SDK-generic pieces (
`ActivationPushNackError`, `encode_push_ack`, `decode_push_ack`) live in
`iota_sdk.p2p`.

The message is serialised via msgpack inside the P2PRouter routed
envelope — see `iota_sdk.p2p.wrap_routed_envelope`.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ActivationPushMessage(BaseModel):
    """Payload pushed from one miner to a peer in the adjacent layer.

    Attributes:
        activation_id:    Stable ID for this activation (generated by the
                          layer-0 miner; preserved throughout the forward and
                          backward journey).
        direction:        ``"forward"`` or ``"backward"``.
        source_hotkey:    SS58 address of the sending miner.
        source_p2p_node_ids:  P2P node IDs of the sender so the
                          recipient can push the backward gradient back.
        tensor_bytes:     ``torch.save``-serialised tensor.
        source_layer:     Training layer index of the sending miner (optional
                          for legacy messages; recipients should validate when set).
        target_layer:     Training layer index of the intended recipient (optional
                          for legacy messages; recipients should validate when set).
    """

    activation_id: str
    direction: str
    source_hotkey: str
    source_p2p_node_ids: list[str] = Field(default_factory=list)
    tensor_bytes: bytes = b""
    # Presigned S3 URL for the original text sample — populated by layer-0 so
    # the last-layer miner can download target labels without querying the orchestrator.
    sample_path: str | None = None
    source_layer: int | None = None
    target_layer: int | None = None
